logging:
  level:
    com:
      xiao9: DEBUG
    org:
      springframework:
        security: DEBUG

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/user?characterEncoding=utf-8&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 123456
    hikari:
      poolName: Hikaris
      auto-commit: false
  jpa:
    show-sql: true
    open-in-view: false
  flyway:
    baseline-on-migrate: true


springfox:
  documentation:
    enabled: true
server:
  port: 8081